---
name: Main
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2, 3.3, 3.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec